/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

'use client';

import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'en' | 'zh';

interface LanguageContextType {
    language: Language;
    setLanguage: (lang: Language) => void;
    t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<Language, Record<string, string>> = {
    en: {
        // Header
        'app.title': 'VectorCraft AI',
        'app.subtitle': 'AI-Powered SVG Generator',
        'header.logout': 'Logout',

        // Login Page
        'login.title': 'Welcome Back',
        'login.subtitle': 'Enter your password to access the SVG generator',
        'login.password.placeholder': 'Enter password',
        'login.button': 'Login',
        'login.button.loading': 'Logging in...',
        'login.session.info': 'Your session will be valid for 24 hours',
        'login.footer': 'AI-Powered Vector Graphics',
        'login.error.required': 'Password is required',
        'login.error.invalid': 'Invalid password',
        'login.error.connection': 'Connection error. Please try again.',

        // Input Section
        'input.title': 'What do you want to create?',
        'input.description': 'Describe an object, icon, or scene, and we\'ll render it as vector art.',
        'input.placeholder': 'e.g. A futuristic cyberpunk helmet with neon lights...',
        'input.button.generate': 'Generate',
        'input.button.generating': 'Crafting...',
        'input.suggestion.1': 'Retro Camera',
        'input.suggestion.2': 'Space Rocket',
        'input.suggestion.3': 'Origami Bird',
        'input.suggestion.4': 'Isometric House',

        // SVG Preview
        'preview.result': 'Result',
        'preview.copy': 'Copy SVG Code',
        'preview.download': 'Download',
        'preview.footer': 'Generated by AI',

        // Empty State
        'empty.message': 'Generated artwork will appear here',

        // Error Messages
        'error.title': 'Generation Failed',
        'error.unauthorized': 'Unauthorized. Please login to use this service.',

        // Language
        'language.current': 'English',
    },
    zh: {
        // Header
        'app.title': 'VectorCraft AI',
        'app.subtitle': 'AI 驱动的 SVG 生成器',
        'header.logout': '登出',

        // Login Page
        'login.title': '欢迎回来',
        'login.subtitle': '请输入密码以访问 SVG 生成器',
        'login.password.placeholder': '输入密码',
        'login.button': '登录',
        'login.button.loading': '登录中...',
        'login.session.info': '您的会话有效期为 24 小时',
        'login.footer': 'AI 驱动的矢量图形生成',
        'login.error.required': '请输入密码',
        'login.error.invalid': '密码错误',
        'login.error.connection': '连接错误，请重试',

        // Input Section
        'input.title': '你想创建什么？',
        'input.description': '描述一个物体、图标或场景，我们将为你呈现为矢量艺术。',
        'input.placeholder': '例如：一个未来主义的赛博朋克头盔，带有霓虹灯...',
        'input.button.generate': '生成',
        'input.button.generating': '创作中...',
        'input.suggestion.1': '复古相机',
        'input.suggestion.2': '太空火箭',
        'input.suggestion.3': '折纸鸟',
        'input.suggestion.4': '等距房屋',

        // SVG Preview
        'preview.result': '结果',
        'preview.copy': '复制 SVG 代码',
        'preview.download': '下载',
        'preview.footer': 'AI 生成',

        // Empty State
        'empty.message': '生成的作品将在此处显示',

        // Error Messages
        'error.title': '生成失败',
        'error.unauthorized': '未授权。请登录以使用此服务。',

        // Language
        'language.current': '简体中文',
    },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
    const [language, setLanguageState] = useState<Language>('en');

    // Load language from localStorage on mount
    useEffect(() => {
        const saved = localStorage.getItem('language') as Language;
        if (saved && (saved === 'en' || saved === 'zh')) {
            setLanguageState(saved);
        }
    }, []);

    const setLanguage = (lang: Language) => {
        setLanguageState(lang);
        localStorage.setItem('language', lang);
    };

    const t = (key: string): string => {
        return translations[language][key] || key;
    };

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
};

export const useLanguage = () => {
    const context = useContext(LanguageContext);
    if (!context) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
};
