/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
*/

import React, { useEffect, useRef } from 'react';
import { Download, CheckCircle2, Code } from 'lucide-react';
import { GeneratedSvg } from '@/types';
import { useLanguage } from '@/contexts/LanguageContext';

interface SvgPreviewProps {
  data: GeneratedSvg | null;
}

export const SvgPreview: React.FC<SvgPreviewProps> = ({ data }) => {
  const { t } = useLanguage();
  const [copied, setCopied] = React.useState(false);
  const containerRef = useRef<HTMLDivElement>(null);

  // Reset copied state when data changes
  useEffect(() => {
    setCopied(false);
  }, [data]);

  if (!data) return null;

  const handleDownload = () => {
    try {
      const blob = new Blob([data.content], { type: 'image/svg+xml' });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `vectorcraft - ${data.id}.svg`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
    } catch (error) {
      console.error('Download failed:', error);
      // Fallback: open in new tab
      const svgBlob = new Blob([data.content], { type: 'image/svg+xml' });
      const url = URL.createObjectURL(svgBlob);
      window.open(url, '_blank');
    }
  };

  const handleCopyCode = async () => {
    try {
      if (navigator.clipboard && navigator.clipboard.writeText) {
        await navigator.clipboard.writeText(data.content);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } else {
        // Fallback for browsers without clipboard API
        const textArea = document.createElement('textarea');
        textArea.value = data.content;
        textArea.style.position = 'fixed';
        textArea.style.left = '-999999px';
        document.body.appendChild(textArea);
        textArea.select();
        document.execCommand('copy');
        document.body.removeChild(textArea);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      }
    } catch (error) {
      console.error('Copy failed:', error);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto mt-12 px-4 animate-in fade-in slide-in-from-bottom-8 duration-700">
      <div className="bg-zinc-900/80 backdrop-blur border border-white/10 rounded-2xl overflow-hidden shadow-2xl">
        {/* Action Buttons */}
        <div className="flex items-center justify-between p-4 bg-zinc-900/50 border-b border-white/5">
          <div className="flex items-center gap-2 text-sm text-zinc-400">
            <CheckCircle2 className="w-4 h-4 text-green-500" />
            <span>{t('preview.result')}</span>
          </div>

          <div className="flex gap-2">
            <button
              onClick={handleCopyCode}
              className={`flex items - center gap - 2 px - 4 py - 2 rounded - lg border transition - colors ${copied
                  ? 'bg-green-500/10 border-green-500/20 text-green-400'
                  : 'bg-zinc-800 hover:bg-zinc-700 border-white/10 text-zinc-300'
                } `}
            >
              <Code className="w-4 h-4" />
              <span className="text-sm">{t('preview.copy')}</span>
            </button>
            <button
              onClick={handleDownload}
              className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white hover:bg-zinc-200 text-zinc-950 transition-colors"
            >
              <Download className="w-4 h-4" />
              <span className="text-sm">{t('preview.download')}</span>
            </button>
          </div>
        </div>

        {/* Canvas Area */}
        <div className="p-8 flex items-center justify-center bg-[url('https://www.transparenttextures.com/patterns/cubes.png')] bg-zinc-950/50 min-h-[400px]">
          {/* 
             Using dangerouslySetInnerHTML is intentional here as the content is generated by the LLM for the purpose of display.
           */}
          <div
            ref={containerRef}
            className="w-full max-w-[512px] h-auto transition-all duration-500 transform hover:scale-[1.02] filter drop-shadow-2xl"
            dangerouslySetInnerHTML={{ __html: data.content }}
          />
        </div>

        {/* Metadata Footer */}
        <div className="px-4 py-2 bg-zinc-950 border-t border-white/5 flex justify-between text-xs text-zinc-600">
          <span>{t('preview.footer')}</span>
        </div>
      </div>
    </div>
  );
};
